config:
  cellOffsetX: 10
  cellOffsetY: 80
  cellWidth: 100
  cellHeight: 100
  cellCountW: 19
  cellCountH: 10
  
  debug:
    tool: BoyDebugTool # none WaypointTool BoyDebugTool
    showWaypoint: false
    showNamedWaypoint: true
    showBoyFoot: false
    showGirlFoot: false

  items:
    catDuration: 5000
    boneDuration: 5000
    policeDuration: 10000
    teenDuration: 5000
    manDuration: 10000

  ui:
    buttons: 
      - item_bone
      - item_cat
      - item_maid
      - item_man
      - item_police
      - item_teen
    panelX: 100
    panelY: 100

    buttonW: 98
    buttonH: 104
    buttonGap: 4
  boy:
    startCellID: 0
    speed: 1
    stayTime: 3000
    mode:
      policeSpeed: 5
      busSpeed: 5
      manSpeed: 0.5
  
  girl:
    startCellID: 15
    speed: 0.7
    stayTime: 5000


  level:
    waypoints:
      # # debug
      # - id: 0
      #   cellX: 0
      #   cellY: 1
      #   connects: [1]
      # - id: 1
      #   cellX: 3
      #   cellY: 1
      #   connects: [0, 2, 3]
      # - id: 2
      #   cellX: 6
      #   cellY: 1
      #   connects: [1, 4]
      # - id: 3
      #   cellX: 3
      #   cellY: 3
      #   connects: [1, 4]
      # - id: 4
      #   cellX: 5
      #   cellY: 3
      #   connects: [2, 3]

      # actual
      - id: 0
        cellX: 0
        cellY: 1
        connects: [1]
      - id: 1
        cellX: 2
        cellY: 1
        connects: [0, 2, 3]
      - id: 2
        cellX: 7
        cellY: 1
        connects: [1, 4]
      - id: 3
        cellX: 2
        cellY: 3
        connects: [1, 4, 5]
      - id: 4
        cellX: 7
        cellY: 3
        connects: [2, 3, 7, 21]
      - id: 5
        cellX: 2
        cellY: 6
        connects: [3, 8, 10, 26]
      - id: 6
        cellX: 7
        cellY: 6
        connects: [7, 27]
      - id: 7
        cellX: 7
        cellY: 5
        connects: [4, 6, 20]
      - id: 8
        name: cafe
        score: 20
        cellX: 0
        cellY: 6
        connects: [5, 9]
      - id: 9
        cellX: 0
        cellY: 9
        connects: [8, 28]
      - id: 10
        cellX: 2
        cellY: 9
        connects: [5, 11, 28]
      - id: 11
        cellX: 7
        cellY: 9
        connects: [10, 12, 31]
      - id: 12
        cellX: 7
        cellY: 8
        connects: [11, 25]
      - id: 13
        cellX: 11
        cellY: 9
        connects: [18, 31, 34]
      - id: 14
        cellX: 17
        cellY: 9
        connects: [29, 34]
      - id: 15
        cellX: 17
        cellY: 6
        connects: [29, 16, 33]
      - id: 16
        cellX: 17
        cellY: 4
        connects: [15, 35, 30]
      - id: 17
        cellX: 17
        cellY: 0
        connects: [30, 24]
      - id: 18
        cellX: 11
        cellY: 6
        connects: [13, 19, 25, 33]
      - id: 19
        name: sports ground
        score: 20
        cellX: 11
        cellY: 4
        connects: [35, 18, 20]
      - id: 20
        cellX: 9
        cellY: 4
        connects: [7, 19]
      - id: 21
        cellX: 9
        cellY: 2
        connects: [4, 32]
      - id: 22
        cellX: 13
        cellY: 2
        connects: [23, 32]
      - id: 23
        cellX: 13
        cellY: 1
        connects: [22, 24]
      - id: 24
        cellX: 15
        cellY: 1
        connects: [17, 23]
      - id: 25
        cellX: 9
        cellY: 8
        connects: [12, 18]
      - id: 26
        name: game center
        score: 20
        cellX: 3
        cellY: 6
        connects: [5, 27]
      - id: 27
        name: animax
        score: 10
        cellX: 5
        cellY: 6
        connects: [6, 26]
      - id: 28
        name: bus stop 1
        score: 0
        cellX: 1
        cellY: 9
        connects: [9, 10]
      - id: 29
        name: bus stop 3
        score: 0
        cellX: 17
        cellY: 8
        connects: [14, 15]
      - id: 30
        name: bus stop 2
        score: 0
        cellX: 17
        cellY: 1
        connects: [16, 17]
      - id: 31
        name: playground
        score: 50
        cellX: 10
        cellY: 9
        connects: [11, 13]
      - id: 32
        name: school
        score: 20
        cellX: 11
        cellY: 2
        connects: [21, 22]
      - id: 33
        name: police station
        score: 10
        cellX: 12
        cellY: 6
        connects: [15, 18]
      - id: 34
        name: park
        score: 10
        cellX: 14
        cellY: 9
        connects: [13, 14]
      - id: 35
        name: hospital
        score: 10
        cellX: 15
        cellY: 4
        connects: [16, 19]
